### ISSUE TITLE
Add bloom post-processing effect to rendering engine.

### ISSUE THREAD

**Issue by tanderegg** [adam4813/Sigma#138]
This will allow for glowing lights and more realistic specular highlights.  Also, will be a component in HDR rendering.

**Comment by wrongu** [comment]
I have a blur shader written on a testing branch: https://github.com/wrongu/Sigma/tree/blur_test
The blending bloom shader would be easy enough to add also.

It would be quick to update and merge this, but I have been waiting on #128 since blur/bloom are not immediately necessary. I'd like to have the pipeline nailed down before adding in new effects.

**Comment by tanderegg** [comment]
Thanks wrongu, I added it primarily because we're looking to add a screen lighting effect to video monitors, which will look much better with a glow added, plus I think it could be useful to have an example of a working post-processing effect before redesigning the pipeline in order to better understand real world needs.  I'm working on a few other things, but if I finish those up I might pick up on this while you work on the pipeline.

**Comment by wrongu** [comment]
The only real difference between the current setup and post-processing is the ability to do texture ping-ponging.

Part of me thinks that examples should come before pipeline, the other part thinks that new effects will just make merging in a new pipeline harder.. But I must admit you're probably right that everyone needs to see examples, and we'll just deal with merge problems later!
