### ISSUE TITLE
Concrete entity class

### ISSUE THREAD

**Issue by adam4813** [adam4813/Sigma#82]
A concrete entity class need to be created. The entity will be used to provide components with position and orientation as well as several convenience methods for changing component state. These include the ability to enable,disable, and destroy an entity and iis components

**Comment by adam4813** [comment]
Also to that end there needs to be a list of entities that storesa shared or unique pointer. Then each component will receive a weak pointer to that smart pointer to allow it to determine if its entity is still valid.

**Comment by wrongu** [comment]
I'm pretty excited for this.

Ultimately, systems will be responsible for removing components of invalid entities, right?

**Comment by adam4813** [comment]
Yes. Potentially through some form of clean up method that gets called
every so often in a gc type manner.

**Comment by catageek** [comment]
As I understood it, an entity would declare components. The Entity constructor registers the entity in the components, and the Entity destructor removes the entity from the component. In other words, the entity was responsible of its own life cycle in the components.

So now we consider the systems as the owner of the lifecycle management of the entity ?

I would rather see a mixed functionment with the entity responsible of its lifecycle in the components it is aware of, and components storing the entity without "declaration" will use a weak_ptr. For instance, the ComputerSessionComponent will store a computer entity as a weak_ptr because the computer entity is not aware of a current session, or an iterator on a entity member will store a weak_ptr because the entity is not aware that an iterator is used on it.

**Comment by adam4813** [comment]
I have found in practice that if the entity controls the life cycle it
makes threading it a pain. If the entity notifies the system to destroy a
component it removes the responsibility for the entity to keep track of how
long the component is alive.

In other words it just makes it easier if the systems have full ownership
of the component to reduce coupling.

Also food for thought on that. What need does the entity have to own its
associated components beyond allowing for easier state change?

**Comment by wrongu** [comment]
@catageek, this was something that I struggled to understand for a while. It's unlike most other ECS implementations. The debate/explanation was held on IRC last month sometime.

And I agree with adam that it should be thought of as a garbage-collector, since that's what it is, and it should probably be implemented as such.

**Comment by aponigricon** [comment]
Damn, you guys are abusing my inbox.

**Comment by catageek** [comment]
Reading carefully [this](http://t-machine.org/index.php/2009/10/26/entity-systems-are-the-future-of-mmos-part-5/) we can see that the entity is itself a simple unique key without functions, but that we must have a table (table 5) giving the components for each entity, and the component data. It is later said that this table can be split for better performance.

So this is how I see this:
- Entity is a simple unique key, no functions, type unsigned int
- EntityManager (the class you describe) holds a map of components per entity (table 5 of the link) and, for better isolation, a set of entity id (table 4 of the link), so that we can reserve an entity id without having to create all the components entries. It can distribute weak_ptrs on entity id to systems and manage the entity id lifecycle and components attachment.
- components data for each entity are stored in data storage that provide a function to make queries on entity id. A component data is retrieved by a query on the storage to get a weak_ptr. A component is merely a getter that use the entity id as key and possibly caches the answer.

So the entity manager does not provide methods to get positions (as you seem to tell), but tells that the entity may have a position component and how to get it. It registers components and bind the component getters. This way, an entity that do not have a position will not have a function to retrieve position.

**Comment by wrongu** [comment]
As I understand it, what you described is a more standard way of doing ECS. Sigma's is sort of different. I should probably let adam give a more thorough response, but the basic idea behind Sigma's ECS is this:
- "Components" are not identical to "resources" as they are in other ECS systems. A Sigma component wraps other resources like position, mesh, etc. Think of the components here more like "the set of data acted on by a given system." So the GL and physics components have _access_ to the position, rotation, and other resources. They are not, themselves, plain data.
- Because nobody has yet come up with an example of an entity without a position value, position/orientation are being treated as a special/optimized case inside an entity _class_
- Components/resources are owned by the systems that use them, because these are the same systems that will destroy them. This makes handling memory across threads easier (still a little fuzzy on that part though)

**Comment by catageek** [comment]
> Because nobody has yet come up with an example of an entity without a position value,
> position/orientation are being treated as a special/optimized case inside an entity class

I have many examples:
- A radar map providing an overview of a region
- A chat session between two or more players
- A shield attached to a ship would not have a position itself
- Items in inventory

All these things do not have a physical presence in the world but are entities (since everything is entity).

Moreover there will be an astronomical world containing objects (stars, galaxy) that are not in the physical world.

So we can't assume that every entity has a position in the physical world. It complicates the system that will manage the world if we put a position to things that don't have a real physical presence. I am for keeping the position as a normal component that will be accessed through normal methods.

Anyway, do we really need an entity class giving access to entity data ? We can access the data by querying the system owning it.

**Comment by adam4813** [comment]
I see where your coming from, and I was there. Having a concrete class is
much easier and reduces coupling. Instead of having to know about an entity
manager each component will just need knowledge of entity.

Also for each entity that doesn't need positron etc does it hurt to have
the useless data.

The approach your describing with querying works well in languages that
provide facilities for that and that have reflection. Sadly c++ lacks both.

We can have a voice chat about the idea at some point if your up for it
guys.

**Comment by catageek** [comment]
> I see where your coming from, and I was there. Having a concrete class is
> much easier and reduces coupling. Instead of having to know about an entity
> manager each component will just need knowledge of entity.

I am just afraid that replacing "component -> entityManager -> component -> data" by "component -> entity -> data" for some components will lead at the end to an entity class hierarchy if more  various data need to be accessed. There are many datas that we may find useful to access through entity. why only the position ?

The question that we must answer is: Will the data be used mostly outside of the systems that own them ?

I would like to know an example of a system that will need positions without owning the position components, and for which the usage justifies that we reduce coupling and we access the data through the entity object instead of accessing it through the EntityManager, or querying the system that owns the positions.

If you provide me an example with such needs, I will certainly understand.

> The approach your describing with querying works well in languages that
> provide facilities for that and that have reflection. Sadly c++ lacks both.

Systems are unique and can be referenced in other systems so that they can query them directly. I don't see the need for reflection here.

> We can have a voice chat about the idea at some point if your up for it

Unfortunately this will be difficult for me.

**Comment by lschmierer** [comment]
Hi, I'm pretty new to the Trillek Project, but I have worked a little time with entity systems in an other project.
I personally would support the opintion of @catageek  of sticking to the good old known way of entity systems (the one explained by the T-Machine: http://t-machine.org/index.php/2009/10/26/entity-systems-are-the-future-of-mmos-part-5/).

I personally don't get the advantage of your suggested way of implementing the entity system; in fact, i think it would realy destroy the concept of the original one...
When thinking about storing the position in an entity class as you suggested... will there be pointers to the corresponding components? What if a component is not used in an entity? Is it pointing to nothing (null)? (Maybe I miss here something specially about C++?¿? I'm a Java Developer ;)) So when a component is added, the entity class has to be updated?

What if I have different obejcts at one special position? (e.g. with a different Mesh Component) I will have to have two entity classes with the same position stored... (and maybe many null pointers) They booth will have the same position...
The original style of entity system would allow to create two entities via the World object (or EntityManger, call it as you want), that would be represented using an id only. So the entity itself would be an integer only, which ist more efficient than an whole object, but also the position would only has to be stored once. It will be stored in an object witch will be matched to the corresponding entityIds int the World/EntityManager (I am used to call it "World ";)). So we will only have to pointers instead of storing the position (after all three floats or doubles) twice.

I think this points out the biggest advantage of the traditional entity system... In my eyes it's the cache-efficeny!!!

<blockquote><blockquote>We can have a voice chat about the idea at some point if your up for it</blockquote>

Unfortunately this will be difficult for me.</blockquote>That woul intrest me, too!

Maybe I am disregarding something in my argumention, I would be happy if you would clear me up ;)
Sorry for my bad english...

**Comment by adam4813** [comment]
Prematrure optimizing on items like caching.

The biggest issue is that C++ lacks reflection. So Determining what a component is in a time consuming process. The tried and true as you make it seem T-Machine article is based around SQL and as such a query based language were getting components is the normal. C++ isn't query based at all and requires storing the items in containers that must be searched. This isn't quite the same but similar. So in order to get a specific component in a specific system my script or what not will need intimate knowledge of both that system and of the component. This increasing coupling and overhead. By having the entity middle man you can just ask for a component and be done with it.

The idea of storing position in entity and not making it a component at all is my goal. Very few entities would have no need for a position and as such they could ignore it and just waste a small amount of memory. If you think hard about it trying to come up with entities that don't use position is actually hard.

**Comment by catageek** [comment]
Components (in the ECS meaning of the word) and systems are well-known. calling entity->getPosition() or WorldPosition->getPosition(id) will not modify the writing of the code, except that writing the component WorldPosition will cost more than storing a variable.

Having knowledge of what an entity is in ECS is an issue. The information must be built on the fly with queries to containers instead of being stored in some objects. But the strength of ECS is that you can build the information very efficiently on a mass of data. To use efficiently ECS, data must be processed massively when needed or, even better, prepared before since we know that it will be needed. So, having knowledge of an entity is an issue, but it is not an issue on a mass of entities.

Another word about the application model: currently Sigma is a client application applying MVC model, but ECS is limited to the "M" of MVC, so systems are in the model. OpenGLSystem is not a system of ECS, it is the controller (the C) for FPSCamera which is the V. It takes data from the model as input and give them to the viewer. The interaction with ECS is only the methods that OpenGL controller will use to access the model. FPSCamera and the GUI are out of scope of ECS.

EDIT: I wonder how you will map the id for the updates received by the network to the instance that needs to be updated.

**Comment by catageek** [comment]
Here the description of the planned design. ECS and Entity hierchachy will coexist and collaborate. Entities will create components and store pointers to them so that we can iterate on a list of entities and access its data without querying the ECS.

On the other side, ECS will provide the modularity of the components,  and will allow to update the data using vectorized batches. Moreover, ECS can structure the data to optimize CPU cache.

# ECS paradigm

In ECS, components are states and entities are IDs. It follows a query pattern like a database.

## Components
- Components are states of the game. In pure ECS, each state become a component.
- Components are mainly primitive data stored in containers such as a map or a vector. They are rarely composite.
- Components will have a class deriving from IComponent and will declare a static componentID
- Components weak pointers will be delivered upon request using entity ID as argument. The pointer will point directly to the data.
- Components are raw data with a getter.

Components will be for example: x, y, z, transform, forces, body, etc.

## Metacomponents
- Metacomponents are objects that store the components container.
- Metacomponents are well known, i.e they are static or accessible from everywhere.
- Components who have the same data lifecycle because they are necessary for a specific feature  should go to the same container. This allows to create easily a feature without adding each component one by one.
- Creation and deletion of components for a specific entity are performed in Metacomponent.
- Functions to get a pointer on raw data are accessible.
- Batches that will operate on raw component data will be stored in metacomponents.
- Dependency between metacomponents must be explicitly managed

An example of Metacomponent is PhysicalWorldLocation that stores x, y, z and the transformation matrix.

# Entity class

Entity is a classic OOP class in a entity class hierarchy.

## Entity
- Helper class to simplify code and reduce the number of components
- Class containing accessors to the components raw data for a specific entity.
- Must add metacomponents to ECS and remove them at entity deletion.
- Stores weak pointers on components, retrieved from the Metacomponents at construction.
- Store the ID of the entity
- May create composite object from data for easier access.
- Represents a game object.
- Must update the pointers when they expire and reconstruct composite objects.
- May update the raw data directly.
- May store entity state data that are not in ECS, for simplicity, if no batch need to be performed. In this case, ECS is not pure since all the states are not components.

Example: BulletMover, FPSCamera, GLMesh are currently entities.

## Entity Manager
- Provide a way to acces to an entity instance by its ID
- Provide a unique GUUID for each entity and the possibility to reuse ID
- Provide factories for each entity type.

# Conclusion

ECS will be used when game states are clearly defined with explicit dependances, and when some modularity or performance is needed.

An Entity class will be created for simplicity and traditional OOP coding, i.e without querying data but accessing it though reference, but will not provide the modularity of ECS since code and data are mixed. If a component is remvoved, the code must take into account this.

**Comment by adam4813** [comment]
Metacomponents would be better named or at least described as component
lookup tables.

**Comment by adam4813** [comment]
Ok I think the debate and discussion are done, and now we are moving into smoothing over a design.

**Comment by catageek** [comment]
40483f8 proposes an implementation. Some critics can be made:
- caller must know the name of the feature to request
- caller does not know the name of components that were exactly created with a specific feature
- caller does not know the type of the component
